name: hackernews
description: A simple package to interact with the HackerNews API.
version: 0.0.1
author: Benoit Layer
homepage: https://github.com/notbenoit/hackernews_api_dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ">=0.12.0"

dev_dependencies:
  test: ^1.11.1